export const data = [
  {
    key: "hero_atlas",
    hero: "Abrams",
    Ability1: "Siphon_Life",
    Ability2: "Shoulder_Charge",
    Ability3: "Infernal_Resilience",
    Ability4: "Seismic_Impact",
  },
  {
    key: "hero_bebop",
    hero: "Bebop",
    Ability1: "Exploding_Uppercut",
    Ability2: "Sticky_Bomb",
    Ability3: "Hook",
    Ability4: "Hyper_Beam",
  },
  {
    key: "hero_dynamo",
    hero: "Dynamo",
    Ability1: "Kinetic_Pulse",
    Ability2: "Quantum_Entanglement",
    Ability3: "Rejuvenating_Aurora",
    Ability4: "Singularity",
  },
  {
    key: "hero_orion",
    hero: "Grey_Talon",
    Ability1: "Charged_Shot",
    Ability2: "Rain_of_Arrows",
    Ability3: "Immobilizing_Trap",
    Ability4: "Guided_Owl",
  },
  {
    key: "hero_haze",
    hero: "Haze",
    Ability1: "Sleep_Dagger",
    Ability2: "Smoke_Bomb",
    Ability3: "Fixation",
    Ability4: "Bullet_Dance",
  },
  {
    key: "hero_inferno",
    hero: "Infernus",
    Ability1: "Catalyst",
    Ability2: "Flame_Dash",
    Ability3: "Afterburn",
    Ability4: "Concussive_Combustion",
  },
  {
    key: "hero_tengu",
    hero: "Ivy",
    Ability1: "Kudzu_Bomb",
    Ability2: "Watcher's_Covenant",
    Ability3: "Stone_Form",
    Ability4: "Air_Drop",
  },
  {
    key: "hero_kelvin",
    hero: "Kelvin",
    Ability1: "Frost_Grenade",
    Ability2: "Ice_Path",
    Ability3: "Arctic_Beam",
    Ability4: "Frozen_Shelter",
  },
  {
    key: "hero_ghost",
    hero: "Lady_Geist",
    Ability1: "Essence_Bomb",
    Ability2: "Life_Drain",
    Ability3: "Malice",
    Ability4: "Soul_Exchange",
  },
  {
    key: "hero_lash",
    hero: "Lash",
    Ability1: "Ground_Strike",
    Ability2: "Grapple",
    Ability3: "Flog",
    Ability4: "Death_Slam",
  },
  {
    key: "hero_forge",
    hero: "McGinnis",
    Ability1: "Mini_Turret",
    Ability2: "Medicinal_Specter",
    Ability3: "Spectral_Wall",
    Ability4: "Heavy_Barrage",
  },
  {
    key: "hero_mirage",
    hero: "Mirage",
    Ability1: "Tornado",
    Ability2: "Fire_Beetles",
    Ability3: "Djinn's_Mark",
    Ability4: "Traveler",
  },
  {
    key: "hero_krill",
    hero: "Mo & Krill",
    Ability1: "Scorn",
    Ability2: "Burrow",
    Ability3: "Sand_Blast",
    Ability4: "Combo",
  },
  {
    key: "hero_chrono",
    hero: "Paradox",
    Ability1: "Pulse_Grenade",
    Ability2: "Time_Wall",
    Ability3: "Kinetic_Carbine",
    Ability4: "Paradoxical_Swap",
  },
  {
    key: "hero_synth",
    hero: "Pocket",
    Ability1: "Barrage",
    Ability2: "Flying_Cloak",
    Ability3: "Enchanter's_Satchel",
    Ability4: "Affliction",
  },
  {
    key: "hero_gigawatt",
    hero: "Seven",
    Ability1: "Lightning_Ball",
    Ability2: "Static_Charge",
    Ability3: "Power_Surge",
    Ability4: "Storm_Cloud",
  },
  {
    key: "hero_shiv",
    hero: "Shiv",
    Ability1: "Serrated_Knives",
    Ability2: "Slice_and_Dice",
    Ability3: "Bloodletting",
    Ability4: "Killing_Blow",
  },
  {
    key: "hero_hornet",
    hero: "Vindicta",
    Ability1: "Stake",
    Ability2: "Flight",
    Ability3: "Crow_Familiar",
    Ability4: "Assassinate",
  },
  {
    key: "hero_viscous",
    hero: "Viscous",
    Ability1: "Splatter",
    Ability2: "The_Cube",
    Ability3: "Puddle_Punch",
    Ability4: "Goo_Ball",
  },
  {
    key: "hero_warden",
    hero: "Warden",
    Ability1: "Alchemical_Flask",
    Ability2: "Willpower",
    Ability3: "Binding_Word",
    Ability4: "Last_Stand",
  },
  {
    key: "hero_wraith",
    hero: "Wraith",
    Ability1: "Card_Trick",
    Ability2: "Project_Mind",
    Ability3: "Full_Auto",
    Ability4: "Telekinesis",
  },
  {
    key: "hero_yamato",
    hero: "Yamato",
    Ability1: "Power_Slash",
    Ability2: "Flying_Strike",
    Ability3: "Crimson_Slash",
    Ability4: "Shadow_Transformation",
  },
];
