export const formatted_conditional_stats = {
  VexBarrierBulletMaxHealth: "Spirit Barrier Bullet Max Health",
  AttackDamageWhenShielded: "Attack Damage When Shielded",
  HealLifePercentOutOfCombat: "Heal Life%Out Of Combat",
  EndRadius: "End Radius",
  FervorFireRate: "Fervor Fire Rate",
  DelayDuration: "Delay Duration",
  SpottedRadius: "Spotted Radius",
  GroundDashReductionPercent: "Ground Dash Reduction%",
  BulletArmorReduction: "Bullet Armor Reduction",
  InteruptCooldown: "Interupt Cooldown",
  FireRateBonus: "Fire Rate Bonus",
  ProcChance: "Proc Chance",
  BaseAttackDamagePercentAtMaxDuration: "Base Attack Damage%At Max Duration",
  BulletDamageReflectedPct: "Bullet Damage Reflected Pct",
  BuildUpDuration: "Build Up Duration",
  ChainTickRate: "Chain Tick Rate",
  Radius: "Radius",
  MovementSpeedBonusDuration: "Movement Speed Bonus Duration",
  SkipFrames: "Skip Frames",
  HeadShotBonusDamage: "Head Shot Bonus Damage",
  LongRangeBonusWeaponPowerMinRange: "Long Range Bonus Weapon Power Min Range",
  EnemyLifeThreshold: "Enemy Life Threshold",
  FlyMoveSpeed: "Fly Move Speed",
  SpiritPowerPerSoul: "Spirit Power Per Soul",
  NonHeroHealPct: "Non Hero Heal Pct",
  StunDuration: "Stun Duration",
  VexBarrierShieldDuration: "Spirit Barrier Shield Duration",
  HealthThreshold: "Health Threshold",
  HeroTargetBonus: "Hero Target Bonus",
  HealFromHero: "Heal From Hero",
  FervorTechResist: "Fervor Tech Resist",
  SelfModifier: "Self Modifier",
  HealAmpRegenPercent: "Heal Amp Regen%",
  ProcBonusMagicDamage: "Proc Bonus Magic Damage",
  TechResist: "Tech Resist",
  SaviorBulletShieldHealth: "Savior Bullet Shield Health",
  MagicIncreasePerStack: "Magic Increase Per Stack",
  RicochetTargetsTooltipOnly: "Ricochet Targets Tooltip Only",
  TickRate: "Tick Rate",
  LifestealPercentHero: "Lifesteal%Hero",
  VisualContractRadius: "Visual Contract Radius",
  RespawnHealthPercent: "Respawn Health%",
  CritDamagePercent: "Crit Damage%",
  TechPower: "Tech Power",
  TechShieldMaxHealth: "Tech Shield Max Health",
  RestoreDelay: "Restore Delay",
  BonusFireRate: "Bonus Fire Rate",
  DebuffDuration: "Debuff Duration",
  BuildUpPerShot: "Build Up Per Shot",
  HealAmpCastPercent: "Heal Amp Cast%",
  FlyingTechShield: "Flying Tech Shield",
  NonHeroReductionPercent: "Non Hero Reduction%",
  SummonDuration: "Summon Duration",
  CloseRangeBonusDamageRange: "Close Range Bonus Damage Range",
  BonusHeavyMeleeDamage: "Bonus Heavy Melee Damage",
  BonusClipSizePercent: "Bonus Clip Size%",
  DPS: "DPS",
  BaseAttackDamagePercentBonus: "Base Attack Damage%Bonus",
  TechArmorDamageReduction: "Tech Armor Damage Reduction",
  BuffDuration: "Buff Duration",
  LongRangeBonusWeaponPower: "Long Range Bonus Weapon Power",
  SlowDuration: "Slow Duration",
  MaxClipBonus: "Max Clip Bonus",
  RicochetDamagePercent: "Ricochet Damage%",
  HealAmpRegenPenaltyPercent: "Heal Amp Regen Penalty%",
  HealFromNPC: "Heal From NPC",
  DamagePulseRadius: "Damage Pulse Radius",
  CastRange: "Cast Range",
  ShreddersTechAmp: "Shredders Tech Amp",
  CloseRangeBonusWeaponPower: "Close Range Bonus Weapon Power",
  Damage: "Damage",
  AmbushBonusTechPower: "Ambush Bonus Tech Power",
  TotalHealthRegen: "Total Health Regen",
  BonusFireRatePlayerUnit: "Bonus Fire Rate Player Unit",
  StunDelay: "Stun Delay",
  MinimumDamage: "Minimum Damage",
  FireRateWhenShielded: "Fire Rate When Shielded",
  HealAmpReceivePenaltyPercent: "Heal Amp Receive Penalty%",
  FervorMovespeed: "Fervor Movespeed",
  DPSMax: "DPSMax",
  SlowResistancePercent: "Slow Resistance%",
  DamagePulseAmount: "Damage Pulse Amount",
  MoveSpeedMax: "Move Speed Max",
  BonusPerChain: "Bonus Per Chain",
  DPSIncrease: "DPSIncrease",
  MaxHealthDamage: "Max Health Damage",
  FullInvisDistance: "Full Invis Distance",
  HealOnKill: "Heal On Kill",
  BaseAttackDamagePercent: "Base Attack Damage%",
  ModelScaleGrowth: "Model Scale Growth",
  AmbushDuration: "Ambush Duration",
  AuraRadius: "Aura Radius",
  InvisMoveSpeedMod: "Invis Move Speed Mod",
  MoveWhileZoomedSpeedPenaltyReductionPercent:
    "Move While Zoomed Speed Penalty Reduction%",
  ShootDurationForMax: "Shoot Duration For Max",
  DotDuration: "Dot Duration",
  TechShieldOnCast: "Tech Shield On Cast",
  LiftHeight: "Lift Height",
  BonusSprintSpeed: "Bonus Sprint Speed",
  LifestealHealPercent: "Lifesteal Heal%",
  EMPDuration: "EMPDuration",
  MaxStacks: "Max Stacks",
  CooldownReductionWithShield: "Cooldown Reduction With Shield",
  DamageDuration: "Damage Duration",
  WeaponPowerPerStack: "Weapon Power Per Stack",
  OutgoingDamagePenaltyPercent: "Outgoing Damage Penalty%",
  HealPercentAmount: "Heal%Amount",
  MagicResistReduction: "Magic Resist Reduction",
  FireRateSlow: "Fire Rate Slow",
  ReProcLockoutTime: "Re Proc Lockout Time",
  DegenResistance: "Degen Resistance",
  StartRadius: "Start Radius",
  BulletResist: "Bullet Resist",
  DamagePerChain: "Damage Per Chain",
  ActiveBonusFireRate: "Active Bonus Fire Rate",
  LifestealHeal: "Lifesteal Heal",
  DampingFactor: "Damping Factor",
  SpiritDamageReflectedPct: "Spirit Damage Reflected Pct",
  TechDamagePercent: "Tech Damage%",
  BulletResistReduction: "Bullet Resist Reduction",
  LowHealthThreshold: "Low Health Threshold",
  ActiveReloadPercent: "Active Reload%",
  ActiveBonusMoveSpeed: "Active Bonus Move Speed",
  AmmoPerSoul: "Ammo Per Soul",
  BonusSpiritWithMagicShield: "Bonus Spirit With Magic Shield",
  BulletShieldOnCast: "Bullet Shield On Cast",
  HealPerStack: "Heal Per Stack",
  RegenDuration: "Regen Duration",
  MaxArmorStacks: "Max Armor Stacks",
  BonusSpirit: "Bonus Spirit",
  HealInterval: "Heal Interval",
  ActiveBonusLifesteal: "Active Bonus Lifesteal",
  MovementSpeedSlow: "Movement Speed Slow",
  FlyingBulletShield: "Flying Bullet Shield",
  BulletLifestealPercent: "Bullet Lifesteal%",
  ChainRadius: "Chain Radius",
  CasterBuffDuration: "Caster Buff Duration",
  SaviorMagicShieldHealth: "Savior Magic Shield Health",
  StatusResistancePercent: "Status Resistance%",
  BulletResistDuration: "Bullet Resist Duration",
  ActivatedFireRate: "Activated Fire Rate",
  AmbushBonusFireRate: "Ambush Bonus Fire Rate",
  HeightOffGround: "Height Off Ground",
  ImpactDamage: "Impact Damage",
  HealPercentPerHeadshot: "Heal%Per Headshot",
  BonusBaseWeaponDamageTaken: "Bonus Base Weapon Damage Taken",
  WeaponPowerPerKill: "Weapon Power Per Kill",
  BonusClipPerKill: "Bonus Clip Per Kill",
  BonusMoveSpeed: "Bonus Move Speed",
  BulletResistPerStack: "Bullet Resist Per Stack",
  ImbuedTechPower: "Imbued Tech Power",
  ProcCooldown: "Proc Cooldown",
  RicochetRadius: "Ricochet Radius",
  SlowPercent: "Slow%",
  BonusClipSize: "Bonus Clip Size",
  SpiritDamage: "Spirit Damage",
  SpreadDuration: "Spread Duration",
  HeadShotCooldown: "Head Shot Cooldown",
  DamageToStack: "Damage To Stack",
  VexBarrierTechMaxHealth: "Spirit Barrier Tech Max Health",
  ChainCount: "Chain Count",
  MoveWhileShootingSpeedPenaltyReductionPercent:
    "Move While Shooting Speed Penalty Reduction%",
  BonusSpiritDuration: "Bonus Spirit Duration",
};
