export const formatted_stats = {
  StealDuration: "Steal Duration",
  NonImbuedCooldownReduction: "Non Imbued Cooldown Reduction",
  BulletLifestealPercent: "Bullet Lifesteal",
  CooldownReduction: "Cooldown Reduction",
  BonusSprintSpeed: "Bonus Sprint Speed",
  StealPerHit: "Steal Per Hit",
  SingleTargetPlayerMultiplier: "Single Target Player Multiplier",
  SlideScale: "Slide Scale",
  Stamina: "Stamina",
  TechRangeMultiplier: "Spirit Range Multiplier",
  SlowDuration: "Slow Duration",
  CastRange: "Cast Range",
  ProcCooldown: "Proc Cooldown",
  ImbuedTechRangeMultiplier: "Imbued Spirit Range Multiplier",
  ImbuedTechRadiusMultiplier: "Imbued Spirit Radius Multiplier",
  ProcChance: "Proc Chance",
  BulletResist: "Bullet Resist",
  TechArmorDamageReduction: "Spirit Armor Damage Reduction",
  BonusClipSizePercent: "Bonus Clip Size",
  ParticleRadius: "Particle Radius",
  BonusClipSize: "Bonus Clip Size",
  LifestrikeHeal: "Lifestrike Heal",
  Radius: "Radius",
  StaminaCooldownReduction: "Stamina Cooldown Reduction",
  LifestealPercentHero: "Lifesteal",
  TechRadiusMultiplier: "Spirit Radius Multiplier",
  StackLostPerDeath: "Stack Lost Per Death",
  BonusAttackRangePercent: "Bonus Attack Range",
  SpiritPower: "Spirit Power",
  TechPower: "Spirit Power",
  MeleeDistanceScale: "Melee Distance Scale",
  ReloadSpeedMultipler: "Reload Speed Multipler",
  LifeThreshold: "Life Threshold",
  CooldownBetweenChargeReduction: "Cooldown Between Charge Reduction",
  CooldownReductionOnChargedAbilities:
    "Cooldown Reduction On Charged Abilities",
  NonImbuedTechRadiusMultiplier: "Non Imbued Spirit Radius Multiplier",
  TechShieldMaxHealth: "Spirit Shield Max Health",
  NonPlayerBulletResist: "Non Player Bullet Resist",
  LocalBulletArmorReduction: "Local Bullet Armor Reduction",
  AirMoveIncreasePercent: "Air Move Increase",
  BonusSpiritForChargedAbilities: "Bonus Spirit For Charged Abilities",
  NonImbuedTechRangeMultiplier: "Non Imbued Spirit Range Multiplier",
  RespawnDelay: "Respawn Delay",
  MaxHealthLossPercent: "Max Health Loss",
  BonusHealthRegen: "Bonus Health Regen",
  ImbuedCooldownReduction: "Imbued Cooldown Reduction",
  BulletShieldMaxHealth: "Bullet Shield Max Health",
  HealthSteal: "Health Steal",
  BonusMeleeDamagePercent: "Melee Damage",
  BaseAttackDamagePercent: "Weapon Damage",
  BonusFireRate: "Bonus Fire Rate",
  TechResist: "Spirit Resist",
  BonusBulletSpeedPercent: "Bonus Bullet Speed",
  BonusAbilityDurationPercent: "Bonus Ability Duration",
  LingerDuration: "Linger Duration",
  BonusAbilityCharges: "Bonus Ability Charges",
  NonImbuedBonusDuration: "Non Imbued Bonus Duration",
  BonusMoveSpeed: "Bonus Move Speed",
  BonusZoomPercent: "Bonus Zoom",
  ImbuedBonusDuration: "Imbued Bonus Duration",
  BonusClipDuration: "Bonus Clip Duration",
  BonusHealth: "Bonus Health",
  SlowPercent: "Slow",
  MaxStacks: "Max Stacks",
  NonPlayerBonusWeaponPower: "Non Player Bonus Weapon Power",
};
